version: '3.9'

services:
  prepared-interview-console:
    image: prepared-interview-console:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: ['yarn', 'start']
    ports:
      - '1234:1234'
